Uncomment permissions, add `contents` read permission
Commenting out the permissions helped with the `checkout` issue we've been
seeing:

```
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/thesis/meso/' not found
```

It's likely because setting specific permission sets all other not specified
permissions to `none`. Now we're looking for the permission we've been missing.
According to
[docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions),
the `contents` permission's scope is this:

> Work with the contents of the repository. For example, contents: read permits
> an action to list the commits, and contents:write allows the action to create
> a release.

This looks like a good candidate.